services:
  _defaults:
    autowire: true
    autoconfigure: true

  Luminoslabs\OroRealTimePricing\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity}'

  oro_pricing.provider.product_price:
    class: 'Luminoslabs\OroRealTimePricing\Provider\RealTimeProductPriceProvider'
    arguments:
      - '@oro_pricing.storage.prices'
      - '@oro_pricing.user_currency_manager'
      - '@oro_config.manager'
      - '@request_stack'
      - !tagged_iterator real_time.pricing.provider
    calls:
      - [setMemoryCacheProvider, ['@oro_pricing.provider.product_price.cache']]

  Luminoslabs\OroRealTimePricing\Controller\Frontend\AjaxRealTimePricesController:
    arguments:
      - !tagged_iterator real_time.pricing.provider
      - '@oro_pricing.model.product_price_scope_criteria_request_handler'

  Luminoslabs\OroRealTimePricing\Service\PricesHelper:
    arguments:
      - '@oro_locale.formatter.number'
      - '@oro_product.formatter.product_unit_value'
      - '@oro_product.formatter.product_unit_label'

  Luminoslabs\OroRealTimePricing\Provider\RealTimePricesConfigProvider:
    arguments:
      - '@oro_config.manager'
    tags:
      - { name: layout.data_provider, alias: real_time_prices_config_provider }
