dynamic-imports:
  realtime:
    - realtime/js/app/views/list-item-product-prices-view
    - realtime/js/app/datagrid/real-time-prices
    - realtime/js/app/components/totals-component

map:
  '*':
    'oroproduct/templates/search-autocomplete.html': 'realtime/templates/search-autocomplete.html'

    'oropricing/js/app/views/list-item-product-prices-view': 'realtime/js/app/views/list-item-product-prices-view'
    'oropricing/js/app/components/totals-component': 'realtime/js/app/components/totals-component'

  'realtime/js/app/views/list-item-product-prices-view':
    'oropricing/js/app/views/list-item-product-prices-view': 'oropricing/js/app/views/list-item-product-prices-view'

  'realtime/js/app/components/totals-component':
    'oropricing/js/app/components/totals-component': 'oropricing/js/app/components/totals-component'
